FROM alpine:3.8
WORKDIR /bin

COPY src/agent/persistence/persistence /bin/

COPY src/agent/persistence/license.txt /bin/license.txt

ENV NAMESPACE ""

# Set Workflow TTL to 7 days
ENV TTL_SECONDS_AFTER_WORKFLOW_FINISH 900
ENV TTL_SECONDS_AFTER_WORKFLOW_DEBUG_MODE 604800

CMD persistence --logtostderr=true --namespace=${NAMESPACE} --ttlSecondsAfterWorkflowFinish=${TTL_SECONDS_AFTER_WORKFLOW_FINISH}  --ttlSecondsAfterWorkflowFinishDebugModle=${TTL_SECONDS_AFTER_WORKFLOW_DEBUG_MODE}
