// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/kubeflow/pipelines/backend/api/run.proto

package go_client

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Run_StorageState int32

const (
	Run_STORAGESTATE_AVAILABLE Run_StorageState = 0
	Run_STORAGESTATE_ARCHIVED  Run_StorageState = 1
)

var Run_StorageState_name = map[int32]string{
	0: "STORAGESTATE_AVAILABLE",
	1: "STORAGESTATE_ARCHIVED",
}

var Run_StorageState_value = map[string]int32{
	"STORAGESTATE_AVAILABLE": 0,
	"STORAGESTATE_ARCHIVED":  1,
}

func (x Run_StorageState) String() string {
	return proto.EnumName(Run_StorageState_name, int32(x))
}

func (Run_StorageState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_62f761e16009c63b, []int{9, 0}
}

type RunMetric_Format int32

const (
	// Default value if not present.
	RunMetric_UNSPECIFIED RunMetric_Format = 0
	// Display value as its raw format.
	RunMetric_RAW RunMetric_Format = 1
	// Display value in percentage format.
	RunMetric_PERCENTAGE RunMetric_Format = 2
)

var RunMetric_Format_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "RAW",
	2: "PERCENTAGE",
}

var RunMetric_Format_value = map[string]int32{
	"UNSPECIFIED": 0,
	"RAW":         1,
	"PERCENTAGE":  2,
}

func (x RunMetric_Format) String() string {
	return proto.EnumName(RunMetric_Format_name, int32(x))
}

func (RunMetric_Format) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_62f761e16009c63b, []int{12, 0}
}

type ReportRunMetricsResponse_ReportRunMetricResult_Status int32

const (
	// Default value if not present.
	ReportRunMetricsResponse_ReportRunMetricResult_UNSPECIFIED ReportRunMetricsResponse_ReportRunMetricResult_Status = 0
	// Indicates successful reporting.
	ReportRunMetricsResponse_ReportRunMetricResult_OK ReportRunMetricsResponse_ReportRunMetricResult_Status = 1
	// Indicates that the payload of the metric is invalid.
	ReportRunMetricsResponse_ReportRunMetricResult_INVALID_ARGUMENT ReportRunMetricsResponse_ReportRunMetricResult_Status = 2
	// Indicates that the metric has been reported before.
	ReportRunMetricsResponse_ReportRunMetricResult_DUPLICATE_REPORTING ReportRunMetricsResponse_ReportRunMetricResult_Status = 3
	// Indicates that something went wrong in the server.
	ReportRunMetricsResponse_ReportRunMetricResult_INTERNAL_ERROR ReportRunMetricsResponse_ReportRunMetricResult_Status = 4
)

var ReportRunMetricsResponse_ReportRunMetricResult_Status_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "OK",
	2: "INVALID_ARGUMENT",
	3: "DUPLICATE_REPORTING",
	4: "INTERNAL_ERROR",
}

var ReportRunMetricsResponse_ReportRunMetricResult_Status_value = map[string]int32{
	"UNSPECIFIED":         0,
	"OK":                  1,
	"INVALID_ARGUMENT":    2,
	"DUPLICATE_REPORTING": 3,
	"INTERNAL_ERROR":      4,
}

func (x ReportRunMetricsResponse_ReportRunMetricResult_Status) String() string {
	return proto.EnumName(ReportRunMetricsResponse_ReportRunMetricResult_Status_name, int32(x))
}

func (ReportRunMetricsResponse_ReportRunMetricResult_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_62f761e16009c63b, []int{14, 0, 0}
}

type CreateRunRequest struct {
	Run                  *Run     `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRunRequest) Reset()         { *m = CreateRunRequest{} }
func (m *CreateRunRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRunRequest) ProtoMessage()    {}
func (*CreateRunRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_62f761e16009c63b, []int{0}
}

func (m *CreateRunRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRunRequest.Unmarshal(m, b)
}
func (m *CreateRunRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRunRequest.Marshal(b, m, deterministic)
}
func (m *CreateRunRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRunRequest.Merge(m, src)
}
func (m *CreateRunRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRunRequest.Size(m)
}
func (m *CreateRunRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRunRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRunRequest proto.InternalMessageInfo

func (m *CreateRunRequest) GetRun() *Run {
	if m != nil {
		return m.Run
	}
	return nil
}

type GetRunRequest struct {
	RunId                string   `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRunRequest) Reset()         { *m = GetRunRequest{} }
func (m *GetRunRequest) String() string { return proto.CompactTextString(m) }
func (*GetRunRequest) ProtoMessage()    {}
func (*GetRunRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_62f761e16009c63b, []int{1}
}

func (m *GetRunRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRunRequest.Unmarshal(m, b)
}
func (m *GetRunRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRunRequest.Marshal(b, m, deterministic)
}
func (m *GetRunRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRunRequest.Merge(m, src)
}
func (m *GetRunRequest) XXX_Size() int {
	return xxx_messageInfo_GetRunRequest.Size(m)
}
func (m *GetRunRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRunRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRunRequest proto.InternalMessageInfo

func (m *GetRunRequest) GetRunId() string {
	if m != nil {
		return m.RunId
	}
	return ""
}

type ListRunsRequest struct {
	PageToken string `protobuf:"bytes,1,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	PageSize  int32  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Can be format of "field_name", "field_name asc" or "field_name des"
	// Ascending by default.
	SortBy string `protobuf:"bytes,3,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	// What resource reference to filter on.
	// E.g. If listing run for an experiment, the query string would be
	// resource_reference_key.type=EXPERIMENT&resource_reference_key.id=123
	ResourceReferenceKey *ResourceKey `protobuf:"bytes,4,opt,name=resource_reference_key,json=resourceReferenceKey,proto3" json:"resource_reference_key,omitempty"`
	// A base-64 encoded, JSON-serialized Filter protocol buffer (see
	// filter.proto).
	Filter               string   `protobuf:"bytes,5,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRunsRequest) Reset()         { *m = ListRunsRequest{} }
func (m *ListRunsRequest) String() string { return proto.CompactTextString(m) }
func (*ListRunsRequest) ProtoMessage()    {}
func (*ListRunsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_62f761e16009c63b, []int{2}
}

func (m *ListRunsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRunsRequest.Unmarshal(m, b)
}
func (m *ListRunsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRunsRequest.Marshal(b, m, deterministic)
}
func (m *ListRunsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRunsRequest.Merge(m, src)
}
func (m *ListRunsRequest) XXX_Size() int {
	return xxx_messageInfo_ListRunsRequest.Size(m)
}
func (m *ListRunsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRunsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRunsRequest proto.InternalMessageInfo

func (m *ListRunsRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

func (m *ListRunsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListRunsRequest) GetSortBy() string {
	if m != nil {
		return m.SortBy
	}
	return ""
}

func (m *ListRunsRequest) GetResourceReferenceKey() *ResourceKey {
	if m != nil {
		return m.ResourceReferenceKey
	}
	return nil
}

func (m *ListRunsRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

type TerminateRunRequest struct {
	RunId                string   `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TerminateRunRequest) Reset()         { *m = TerminateRunRequest{} }
func (m *TerminateRunRequest) String() string { return proto.CompactTextString(m) }
func (*TerminateRunRequest) ProtoMessage()    {}
func (*TerminateRunRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_62f761e16009c63b, []int{3}
}

func (m *TerminateRunRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TerminateRunRequest.Unmarshal(m, b)
}
func (m *TerminateRunRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TerminateRunRequest.Marshal(b, m, deterministic)
}
func (m *TerminateRunRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TerminateRunRequest.Merge(m, src)
}
func (m *TerminateRunRequest) XXX_Size() int {
	return xxx_messageInfo_TerminateRunRequest.Size(m)
}
func (m *TerminateRunRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TerminateRunRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TerminateRunRequest proto.InternalMessageInfo

func (m *TerminateRunRequest) GetRunId() string {
	if m != nil {
		return m.RunId
	}
	return ""
}

type RetryRunRequest struct {
	RunId                string   `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetryRunRequest) Reset()         { *m = RetryRunRequest{} }
func (m *RetryRunRequest) String() string { return proto.CompactTextString(m) }
func (*RetryRunRequest) ProtoMessage()    {}
func (*RetryRunRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_62f761e16009c63b, []int{4}
}

func (m *RetryRunRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetryRunRequest.Unmarshal(m, b)
}
func (m *RetryRunRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetryRunRequest.Marshal(b, m, deterministic)
}
func (m *RetryRunRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetryRunRequest.Merge(m, src)
}
func (m *RetryRunRequest) XXX_Size() int {
	return xxx_messageInfo_RetryRunRequest.Size(m)
}
func (m *RetryRunRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetryRunRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetryRunRequest proto.InternalMessageInfo

func (m *RetryRunRequest) GetRunId() string {
	if m != nil {
		return m.RunId
	}
	return ""
}

type ListRunsResponse struct {
	Runs                 []*Run   `protobuf:"bytes,1,rep,name=runs,proto3" json:"runs,omitempty"`
	TotalSize            int32    `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	NextPageToken        string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRunsResponse) Reset()         { *m = ListRunsResponse{} }
func (m *ListRunsResponse) String() string { return proto.CompactTextString(m) }
func (*ListRunsResponse) ProtoMessage()    {}
func (*ListRunsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_62f761e16009c63b, []int{5}
}

func (m *ListRunsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRunsResponse.Unmarshal(m, b)
}
func (m *ListRunsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRunsResponse.Marshal(b, m, deterministic)
}
func (m *ListRunsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRunsResponse.Merge(m, src)
}
func (m *ListRunsResponse) XXX_Size() int {
	return xxx_messageInfo_ListRunsResponse.Size(m)
}
func (m *ListRunsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRunsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListRunsResponse proto.InternalMessageInfo

func (m *ListRunsResponse) GetRuns() []*Run {
	if m != nil {
		return m.Runs
	}
	return nil
}

func (m *ListRunsResponse) GetTotalSize() int32 {
	if m != nil {
		return m.TotalSize
	}
	return 0
}

func (m *ListRunsResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type ArchiveRunRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArchiveRunRequest) Reset()         { *m = ArchiveRunRequest{} }
func (m *ArchiveRunRequest) String() string { return proto.CompactTextString(m) }
func (*ArchiveRunRequest) ProtoMessage()    {}
func (*ArchiveRunRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_62f761e16009c63b, []int{6}
}

func (m *ArchiveRunRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArchiveRunRequest.Unmarshal(m, b)
}
func (m *ArchiveRunRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArchiveRunRequest.Marshal(b, m, deterministic)
}
func (m *ArchiveRunRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArchiveRunRequest.Merge(m, src)
}
func (m *ArchiveRunRequest) XXX_Size() int {
	return xxx_messageInfo_ArchiveRunRequest.Size(m)
}
func (m *ArchiveRunRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ArchiveRunRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ArchiveRunRequest proto.InternalMessageInfo

func (m *ArchiveRunRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UnarchiveRunRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnarchiveRunRequest) Reset()         { *m = UnarchiveRunRequest{} }
func (m *UnarchiveRunRequest) String() string { return proto.CompactTextString(m) }
func (*UnarchiveRunRequest) ProtoMessage()    {}
func (*UnarchiveRunRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_62f761e16009c63b, []int{7}
}

func (m *UnarchiveRunRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnarchiveRunRequest.Unmarshal(m, b)
}
func (m *UnarchiveRunRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnarchiveRunRequest.Marshal(b, m, deterministic)
}
func (m *UnarchiveRunRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnarchiveRunRequest.Merge(m, src)
}
func (m *UnarchiveRunRequest) XXX_Size() int {
	return xxx_messageInfo_UnarchiveRunRequest.Size(m)
}
func (m *UnarchiveRunRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnarchiveRunRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnarchiveRunRequest proto.InternalMessageInfo

func (m *UnarchiveRunRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteRunRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRunRequest) Reset()         { *m = DeleteRunRequest{} }
func (m *DeleteRunRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRunRequest) ProtoMessage()    {}
func (*DeleteRunRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_62f761e16009c63b, []int{8}
}

func (m *DeleteRunRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRunRequest.Unmarshal(m, b)
}
func (m *DeleteRunRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRunRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRunRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRunRequest.Merge(m, src)
}
func (m *DeleteRunRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRunRequest.Size(m)
}
func (m *DeleteRunRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRunRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRunRequest proto.InternalMessageInfo

func (m *DeleteRunRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Run struct {
	// Output. Unique run ID. Generated by API server.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Required input field. Name provided by user,
	// or auto generated if run is created by scheduled job. Not unique.
	Name         string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Debug        string           `protobuf:"bytes,14,opt,name=debug,proto3" json:"debug,omitempty"`
	StorageState Run_StorageState `protobuf:"varint,10,opt,name=storage_state,json=storageState,proto3,enum=api.Run_StorageState" json:"storage_state,omitempty"`
	// Optional input field. Describing the purpose of the run
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Required input field.
	// Describing what the pipeline manifest and parameters to use for the run.
	PipelineSpec *PipelineSpec `protobuf:"bytes,4,opt,name=pipeline_spec,json=pipelineSpec,proto3" json:"pipeline_spec,omitempty"`
	// Optional input field. Specify which resource this run belongs to.
	ResourceReferences []*ResourceReference `protobuf:"bytes,5,rep,name=resource_references,json=resourceReferences,proto3" json:"resource_references,omitempty"`
	// Output. The time that the run created.
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Output. When this run is scheduled to run. This could be different from
	// created_at. For example, if a run is from a backfilling job that was
	// supposed to run 2 month ago, the scheduled_at is 2 month ago,
	// v.s. created_at is the current time.
	ScheduledAt *timestamp.Timestamp `protobuf:"bytes,7,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	// Output. The time this run is finished.
	FinishedAt *timestamp.Timestamp `protobuf:"bytes,13,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	// Output. The status of the run.
	// One of [Pending, Running, Succeeded, Skipped, Failed, Error]
	Status string `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	// In case any error happens retrieving a run field, only run ID
	// and the error message is returned. Client has the flexibility of choosing
	// how to handle error. This is especially useful during listing call.
	Error string `protobuf:"bytes,12,opt,name=error,proto3" json:"error,omitempty"`
	// Output. The metrics of the run. The metrics are reported by ReportMetrics
	// API.
	Metrics              []*RunMetric `protobuf:"bytes,9,rep,name=metrics,proto3" json:"metrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Run) Reset()         { *m = Run{} }
func (m *Run) String() string { return proto.CompactTextString(m) }
func (*Run) ProtoMessage()    {}
func (*Run) Descriptor() ([]byte, []int) {
	return fileDescriptor_62f761e16009c63b, []int{9}
}

func (m *Run) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Run.Unmarshal(m, b)
}
func (m *Run) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Run.Marshal(b, m, deterministic)
}
func (m *Run) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Run.Merge(m, src)
}
func (m *Run) XXX_Size() int {
	return xxx_messageInfo_Run.Size(m)
}
func (m *Run) XXX_DiscardUnknown() {
	xxx_messageInfo_Run.DiscardUnknown(m)
}

var xxx_messageInfo_Run proto.InternalMessageInfo

func (m *Run) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Run) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Run) GetDebug() string {
	if m != nil {
		return m.Debug
	}
	return ""
}

func (m *Run) GetStorageState() Run_StorageState {
	if m != nil {
		return m.StorageState
	}
	return Run_STORAGESTATE_AVAILABLE
}

func (m *Run) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Run) GetPipelineSpec() *PipelineSpec {
	if m != nil {
		return m.PipelineSpec
	}
	return nil
}

func (m *Run) GetResourceReferences() []*ResourceReference {
	if m != nil {
		return m.ResourceReferences
	}
	return nil
}

func (m *Run) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Run) GetScheduledAt() *timestamp.Timestamp {
	if m != nil {
		return m.ScheduledAt
	}
	return nil
}

func (m *Run) GetFinishedAt() *timestamp.Timestamp {
	if m != nil {
		return m.FinishedAt
	}
	return nil
}

func (m *Run) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Run) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Run) GetMetrics() []*RunMetric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

type PipelineRuntime struct {
	// Output. The runtime JSON manifest of the pipeline, including the status
	// of pipeline steps and fields need for UI visualization etc.
	PipelineManifest string `protobuf:"bytes,10,opt,name=pipeline_manifest,json=pipelineManifest,proto3" json:"pipeline_manifest,omitempty"`
	// Output. The runtime JSON manifest of the argo workflow.
	// This is deprecated after pipeline_runtime_manifest is in use.
	WorkflowManifest     string   `protobuf:"bytes,11,opt,name=workflow_manifest,json=workflowManifest,proto3" json:"workflow_manifest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PipelineRuntime) Reset()         { *m = PipelineRuntime{} }
func (m *PipelineRuntime) String() string { return proto.CompactTextString(m) }
func (*PipelineRuntime) ProtoMessage()    {}
func (*PipelineRuntime) Descriptor() ([]byte, []int) {
	return fileDescriptor_62f761e16009c63b, []int{10}
}

func (m *PipelineRuntime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PipelineRuntime.Unmarshal(m, b)
}
func (m *PipelineRuntime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PipelineRuntime.Marshal(b, m, deterministic)
}
func (m *PipelineRuntime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PipelineRuntime.Merge(m, src)
}
func (m *PipelineRuntime) XXX_Size() int {
	return xxx_messageInfo_PipelineRuntime.Size(m)
}
func (m *PipelineRuntime) XXX_DiscardUnknown() {
	xxx_messageInfo_PipelineRuntime.DiscardUnknown(m)
}

var xxx_messageInfo_PipelineRuntime proto.InternalMessageInfo

func (m *PipelineRuntime) GetPipelineManifest() string {
	if m != nil {
		return m.PipelineManifest
	}
	return ""
}

func (m *PipelineRuntime) GetWorkflowManifest() string {
	if m != nil {
		return m.WorkflowManifest
	}
	return ""
}

type RunDetail struct {
	Run                  *Run             `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	PipelineRuntime      *PipelineRuntime `protobuf:"bytes,2,opt,name=pipeline_runtime,json=pipelineRuntime,proto3" json:"pipeline_runtime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RunDetail) Reset()         { *m = RunDetail{} }
func (m *RunDetail) String() string { return proto.CompactTextString(m) }
func (*RunDetail) ProtoMessage()    {}
func (*RunDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_62f761e16009c63b, []int{11}
}

func (m *RunDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunDetail.Unmarshal(m, b)
}
func (m *RunDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunDetail.Marshal(b, m, deterministic)
}
func (m *RunDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunDetail.Merge(m, src)
}
func (m *RunDetail) XXX_Size() int {
	return xxx_messageInfo_RunDetail.Size(m)
}
func (m *RunDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_RunDetail.DiscardUnknown(m)
}

var xxx_messageInfo_RunDetail proto.InternalMessageInfo

func (m *RunDetail) GetRun() *Run {
	if m != nil {
		return m.Run
	}
	return nil
}

func (m *RunDetail) GetPipelineRuntime() *PipelineRuntime {
	if m != nil {
		return m.PipelineRuntime
	}
	return nil
}

type RunMetric struct {
	// Required. The user defined name of the metric. It must between 1 and 63 characters
	// long and must conform to the following regular expression:
	// `[a-z]([-a-z0-9]*[a-z0-9])?`.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Required. The runtime node ID which reports the metric. The node ID can be found in
	// the RunDetail.workflow.Status. Metric with same (node_id, name)
	// are considerd as duplicate. Only the first reporting will be recorded. Max length is 128.
	NodeId string `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*RunMetric_NumberValue
	Value isRunMetric_Value `protobuf_oneof:"value"`
	// The display format of metric.
	Format               RunMetric_Format `protobuf:"varint,4,opt,name=format,proto3,enum=api.RunMetric_Format" json:"format,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RunMetric) Reset()         { *m = RunMetric{} }
func (m *RunMetric) String() string { return proto.CompactTextString(m) }
func (*RunMetric) ProtoMessage()    {}
func (*RunMetric) Descriptor() ([]byte, []int) {
	return fileDescriptor_62f761e16009c63b, []int{12}
}

func (m *RunMetric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunMetric.Unmarshal(m, b)
}
func (m *RunMetric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunMetric.Marshal(b, m, deterministic)
}
func (m *RunMetric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunMetric.Merge(m, src)
}
func (m *RunMetric) XXX_Size() int {
	return xxx_messageInfo_RunMetric.Size(m)
}
func (m *RunMetric) XXX_DiscardUnknown() {
	xxx_messageInfo_RunMetric.DiscardUnknown(m)
}

var xxx_messageInfo_RunMetric proto.InternalMessageInfo

func (m *RunMetric) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RunMetric) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

type isRunMetric_Value interface {
	isRunMetric_Value()
}

type RunMetric_NumberValue struct {
	NumberValue float64 `protobuf:"fixed64,3,opt,name=number_value,json=numberValue,proto3,oneof"`
}

func (*RunMetric_NumberValue) isRunMetric_Value() {}

func (m *RunMetric) GetValue() isRunMetric_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *RunMetric) GetNumberValue() float64 {
	if x, ok := m.GetValue().(*RunMetric_NumberValue); ok {
		return x.NumberValue
	}
	return 0
}

func (m *RunMetric) GetFormat() RunMetric_Format {
	if m != nil {
		return m.Format
	}
	return RunMetric_UNSPECIFIED
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RunMetric) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RunMetric_NumberValue)(nil),
	}
}

type ReportRunMetricsRequest struct {
	// Required. The parent run ID of the metric.
	RunId string `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// List of metrics to report.
	Metrics              []*RunMetric `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReportRunMetricsRequest) Reset()         { *m = ReportRunMetricsRequest{} }
func (m *ReportRunMetricsRequest) String() string { return proto.CompactTextString(m) }
func (*ReportRunMetricsRequest) ProtoMessage()    {}
func (*ReportRunMetricsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_62f761e16009c63b, []int{13}
}

func (m *ReportRunMetricsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportRunMetricsRequest.Unmarshal(m, b)
}
func (m *ReportRunMetricsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportRunMetricsRequest.Marshal(b, m, deterministic)
}
func (m *ReportRunMetricsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportRunMetricsRequest.Merge(m, src)
}
func (m *ReportRunMetricsRequest) XXX_Size() int {
	return xxx_messageInfo_ReportRunMetricsRequest.Size(m)
}
func (m *ReportRunMetricsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportRunMetricsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReportRunMetricsRequest proto.InternalMessageInfo

func (m *ReportRunMetricsRequest) GetRunId() string {
	if m != nil {
		return m.RunId
	}
	return ""
}

func (m *ReportRunMetricsRequest) GetMetrics() []*RunMetric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

type ReportRunMetricsResponse struct {
	Results              []*ReportRunMetricsResponse_ReportRunMetricResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                          `json:"-"`
	XXX_unrecognized     []byte                                            `json:"-"`
	XXX_sizecache        int32                                             `json:"-"`
}

func (m *ReportRunMetricsResponse) Reset()         { *m = ReportRunMetricsResponse{} }
func (m *ReportRunMetricsResponse) String() string { return proto.CompactTextString(m) }
func (*ReportRunMetricsResponse) ProtoMessage()    {}
func (*ReportRunMetricsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_62f761e16009c63b, []int{14}
}

func (m *ReportRunMetricsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportRunMetricsResponse.Unmarshal(m, b)
}
func (m *ReportRunMetricsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportRunMetricsResponse.Marshal(b, m, deterministic)
}
func (m *ReportRunMetricsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportRunMetricsResponse.Merge(m, src)
}
func (m *ReportRunMetricsResponse) XXX_Size() int {
	return xxx_messageInfo_ReportRunMetricsResponse.Size(m)
}
func (m *ReportRunMetricsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportRunMetricsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReportRunMetricsResponse proto.InternalMessageInfo

func (m *ReportRunMetricsResponse) GetResults() []*ReportRunMetricsResponse_ReportRunMetricResult {
	if m != nil {
		return m.Results
	}
	return nil
}

type ReportRunMetricsResponse_ReportRunMetricResult struct {
	// Output. The name of the metric.
	MetricName string `protobuf:"bytes,1,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	// Output. The ID of the node which reports the metric.
	MetricNodeId string `protobuf:"bytes,2,opt,name=metric_node_id,json=metricNodeId,proto3" json:"metric_node_id,omitempty"`
	// Output. The status of the metric reporting.
	Status ReportRunMetricsResponse_ReportRunMetricResult_Status `protobuf:"varint,3,opt,name=status,proto3,enum=api.ReportRunMetricsResponse_ReportRunMetricResult_Status" json:"status,omitempty"`
	// Output. The detailed message of the error of the reporting.
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportRunMetricsResponse_ReportRunMetricResult) Reset() {
	*m = ReportRunMetricsResponse_ReportRunMetricResult{}
}
func (m *ReportRunMetricsResponse_ReportRunMetricResult) String() string {
	return proto.CompactTextString(m)
}
func (*ReportRunMetricsResponse_ReportRunMetricResult) ProtoMessage() {}
func (*ReportRunMetricsResponse_ReportRunMetricResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_62f761e16009c63b, []int{14, 0}
}

func (m *ReportRunMetricsResponse_ReportRunMetricResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportRunMetricsResponse_ReportRunMetricResult.Unmarshal(m, b)
}
func (m *ReportRunMetricsResponse_ReportRunMetricResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportRunMetricsResponse_ReportRunMetricResult.Marshal(b, m, deterministic)
}
func (m *ReportRunMetricsResponse_ReportRunMetricResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportRunMetricsResponse_ReportRunMetricResult.Merge(m, src)
}
func (m *ReportRunMetricsResponse_ReportRunMetricResult) XXX_Size() int {
	return xxx_messageInfo_ReportRunMetricsResponse_ReportRunMetricResult.Size(m)
}
func (m *ReportRunMetricsResponse_ReportRunMetricResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportRunMetricsResponse_ReportRunMetricResult.DiscardUnknown(m)
}

var xxx_messageInfo_ReportRunMetricsResponse_ReportRunMetricResult proto.InternalMessageInfo

func (m *ReportRunMetricsResponse_ReportRunMetricResult) GetMetricName() string {
	if m != nil {
		return m.MetricName
	}
	return ""
}

func (m *ReportRunMetricsResponse_ReportRunMetricResult) GetMetricNodeId() string {
	if m != nil {
		return m.MetricNodeId
	}
	return ""
}

func (m *ReportRunMetricsResponse_ReportRunMetricResult) GetStatus() ReportRunMetricsResponse_ReportRunMetricResult_Status {
	if m != nil {
		return m.Status
	}
	return ReportRunMetricsResponse_ReportRunMetricResult_UNSPECIFIED
}

func (m *ReportRunMetricsResponse_ReportRunMetricResult) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ReadArtifactRequest struct {
	// The ID of the run.
	RunId string `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// The ID of the running node.
	NodeId string `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// The name of the artifact.
	ArtifactName         string   `protobuf:"bytes,3,opt,name=artifact_name,json=artifactName,proto3" json:"artifact_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadArtifactRequest) Reset()         { *m = ReadArtifactRequest{} }
func (m *ReadArtifactRequest) String() string { return proto.CompactTextString(m) }
func (*ReadArtifactRequest) ProtoMessage()    {}
func (*ReadArtifactRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_62f761e16009c63b, []int{15}
}

func (m *ReadArtifactRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadArtifactRequest.Unmarshal(m, b)
}
func (m *ReadArtifactRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadArtifactRequest.Marshal(b, m, deterministic)
}
func (m *ReadArtifactRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadArtifactRequest.Merge(m, src)
}
func (m *ReadArtifactRequest) XXX_Size() int {
	return xxx_messageInfo_ReadArtifactRequest.Size(m)
}
func (m *ReadArtifactRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadArtifactRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadArtifactRequest proto.InternalMessageInfo

func (m *ReadArtifactRequest) GetRunId() string {
	if m != nil {
		return m.RunId
	}
	return ""
}

func (m *ReadArtifactRequest) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *ReadArtifactRequest) GetArtifactName() string {
	if m != nil {
		return m.ArtifactName
	}
	return ""
}

type ReadArtifactResponse struct {
	// The bytes of the artifact content.
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadArtifactResponse) Reset()         { *m = ReadArtifactResponse{} }
func (m *ReadArtifactResponse) String() string { return proto.CompactTextString(m) }
func (*ReadArtifactResponse) ProtoMessage()    {}
func (*ReadArtifactResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_62f761e16009c63b, []int{16}
}

func (m *ReadArtifactResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadArtifactResponse.Unmarshal(m, b)
}
func (m *ReadArtifactResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadArtifactResponse.Marshal(b, m, deterministic)
}
func (m *ReadArtifactResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadArtifactResponse.Merge(m, src)
}
func (m *ReadArtifactResponse) XXX_Size() int {
	return xxx_messageInfo_ReadArtifactResponse.Size(m)
}
func (m *ReadArtifactResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadArtifactResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadArtifactResponse proto.InternalMessageInfo

func (m *ReadArtifactResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("api.Run_StorageState", Run_StorageState_name, Run_StorageState_value)
	proto.RegisterEnum("api.RunMetric_Format", RunMetric_Format_name, RunMetric_Format_value)
	proto.RegisterEnum("api.ReportRunMetricsResponse_ReportRunMetricResult_Status", ReportRunMetricsResponse_ReportRunMetricResult_Status_name, ReportRunMetricsResponse_ReportRunMetricResult_Status_value)
	proto.RegisterType((*CreateRunRequest)(nil), "api.CreateRunRequest")
	proto.RegisterType((*GetRunRequest)(nil), "api.GetRunRequest")
	proto.RegisterType((*ListRunsRequest)(nil), "api.ListRunsRequest")
	proto.RegisterType((*TerminateRunRequest)(nil), "api.TerminateRunRequest")
	proto.RegisterType((*RetryRunRequest)(nil), "api.RetryRunRequest")
	proto.RegisterType((*ListRunsResponse)(nil), "api.ListRunsResponse")
	proto.RegisterType((*ArchiveRunRequest)(nil), "api.ArchiveRunRequest")
	proto.RegisterType((*UnarchiveRunRequest)(nil), "api.UnarchiveRunRequest")
	proto.RegisterType((*DeleteRunRequest)(nil), "api.DeleteRunRequest")
	proto.RegisterType((*Run)(nil), "api.Run")
	proto.RegisterType((*PipelineRuntime)(nil), "api.PipelineRuntime")
	proto.RegisterType((*RunDetail)(nil), "api.RunDetail")
	proto.RegisterType((*RunMetric)(nil), "api.RunMetric")
	proto.RegisterType((*ReportRunMetricsRequest)(nil), "api.ReportRunMetricsRequest")
	proto.RegisterType((*ReportRunMetricsResponse)(nil), "api.ReportRunMetricsResponse")
	proto.RegisterType((*ReportRunMetricsResponse_ReportRunMetricResult)(nil), "api.ReportRunMetricsResponse.ReportRunMetricResult")
	proto.RegisterType((*ReadArtifactRequest)(nil), "api.ReadArtifactRequest")
	proto.RegisterType((*ReadArtifactResponse)(nil), "api.ReadArtifactResponse")
}

func init() {
	proto.RegisterFile("github.com/kubeflow/pipelines/backend/api/run.proto", fileDescriptor_62f761e16009c63b)
}

var fileDescriptor_62f761e16009c63b = []byte{
	// 1571 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0xdd, 0x4e, 0xe3, 0xda,
	0x15, 0xc6, 0x09, 0x24, 0x64, 0x25, 0x01, 0xb3, 0xf9, 0xf3, 0x64, 0x40, 0x70, 0xcc, 0xf9, 0xe1,
	0x4c, 0x0f, 0x89, 0x0e, 0x53, 0x55, 0x2a, 0x55, 0x55, 0x19, 0xc8, 0x70, 0xd2, 0x81, 0x40, 0x77,
	0x02, 0x95, 0xa6, 0x17, 0x96, 0x63, 0xef, 0x04, 0x97, 0xc4, 0x76, 0xf7, 0xde, 0x86, 0x32, 0xa3,
	0xb9, 0xa9, 0x74, 0x5e, 0xa0, 0xbd, 0xe8, 0x5d, 0x1f, 0xe2, 0x3c, 0x44, 0xa5, 0x5e, 0xf7, 0x15,
	0xfa, 0x08, 0x7d, 0x80, 0xca, 0x7b, 0xdb, 0x19, 0xe7, 0x87, 0xa0, 0xce, 0x15, 0xec, 0xb5, 0xbe,
	0xf5, 0x93, 0xb5, 0xd6, 0xb7, 0xb2, 0x02, 0xaf, 0x7b, 0x2e, 0xbf, 0x0d, 0x3b, 0x55, 0xdb, 0x1f,
	0xd4, 0xee, 0xc2, 0x0e, 0xe9, 0xf6, 0xfd, 0x87, 0x5a, 0xe0, 0x06, 0xa4, 0xef, 0x7a, 0x84, 0xd5,
	0x3a, 0x96, 0x7d, 0x47, 0x3c, 0xa7, 0x66, 0x05, 0x6e, 0x8d, 0x86, 0x5e, 0x35, 0xa0, 0x3e, 0xf7,
	0x51, 0xd6, 0x0a, 0xdc, 0xca, 0x66, 0x5a, 0x47, 0x28, 0xf5, 0xa9, 0xd4, 0x56, 0x5e, 0xf6, 0x7c,
	0xbf, 0xd7, 0x27, 0x35, 0xf1, 0xea, 0x84, 0xdd, 0x1a, 0x19, 0x04, 0xfc, 0x31, 0x56, 0x6e, 0xc5,
	0xca, 0xc8, 0xc8, 0xf2, 0x3c, 0x9f, 0x5b, 0xdc, 0xf5, 0x3d, 0x16, 0x6b, 0x77, 0xc6, 0x4d, 0xb9,
	0x3b, 0x20, 0x8c, 0x5b, 0x83, 0x20, 0x01, 0xa4, 0x83, 0x26, 0x69, 0x9a, 0x2c, 0x20, 0x76, 0x0c,
	0xf8, 0x72, 0x24, 0x63, 0xc2, 0xfc, 0x90, 0xda, 0xc4, 0xa4, 0xa4, 0x4b, 0x28, 0xf1, 0x6c, 0x12,
	0xa3, 0xbe, 0x13, 0x7f, 0xec, 0x83, 0x1e, 0xf1, 0x0e, 0xd8, 0x83, 0xd5, 0xeb, 0x11, 0x5a, 0xf3,
	0x03, 0x91, 0xc9, 0x64, 0x56, 0x7a, 0x15, 0xd4, 0x13, 0x4a, 0x2c, 0x4e, 0x70, 0xe8, 0x61, 0xf2,
	0xa7, 0x90, 0x30, 0x8e, 0x2a, 0x90, 0xa5, 0xa1, 0xa7, 0x29, 0xbb, 0xca, 0x7e, 0xf1, 0x70, 0xb1,
	0x6a, 0x05, 0x6e, 0x35, 0xd2, 0x46, 0x42, 0xfd, 0x6b, 0x28, 0x9f, 0x11, 0x9e, 0x02, 0xaf, 0x43,
	0x8e, 0x86, 0x9e, 0xe9, 0x3a, 0x02, 0x5f, 0xc0, 0x0b, 0x34, 0xf4, 0x1a, 0x8e, 0xfe, 0x4f, 0x05,
	0x96, 0xcf, 0x5d, 0x16, 0x21, 0x59, 0x02, 0xdd, 0x06, 0x08, 0xac, 0x1e, 0x31, 0xb9, 0x7f, 0x47,
	0xbc, 0x18, 0x5e, 0x88, 0x24, 0xed, 0x48, 0x80, 0x5e, 0x82, 0x78, 0x98, 0xcc, 0x7d, 0x4f, 0xb4,
	0xcc, 0xae, 0xb2, 0xbf, 0x80, 0x17, 0x23, 0x41, 0xcb, 0x7d, 0x4f, 0xd0, 0x26, 0xe4, 0x99, 0x4f,
	0xb9, 0xd9, 0x79, 0xd4, 0xb2, 0xc2, 0x30, 0x17, 0x3d, 0x8f, 0x1f, 0xd1, 0x1b, 0xd8, 0x98, 0x2c,
	0x85, 0x79, 0x47, 0x1e, 0xb5, 0x79, 0x91, 0xbf, 0x2a, 0xf3, 0x8f, 0x21, 0x6f, 0xc9, 0x23, 0x5e,
	0x4b, 0xf0, 0x38, 0x81, 0xbf, 0x25, 0x8f, 0x68, 0x03, 0x72, 0x5d, 0xb7, 0xcf, 0x09, 0xd5, 0x16,
	0xa4, 0x7f, 0xf9, 0xd2, 0xbf, 0x83, 0xd5, 0x36, 0xa1, 0x03, 0xd7, 0x1b, 0xad, 0xd1, 0x13, 0x1f,
	0x7b, 0x1f, 0x96, 0x31, 0xe1, 0xf4, 0xf1, 0x79, 0xe4, 0x03, 0xa8, 0x9f, 0xea, 0xc3, 0x02, 0xdf,
	0x63, 0x04, 0x6d, 0xc1, 0x3c, 0x0d, 0x3d, 0xa6, 0x29, 0xbb, 0xd9, 0x91, 0xca, 0x0b, 0x69, 0x54,
	0x3e, 0xee, 0x73, 0xab, 0x2f, 0x0b, 0x94, 0x15, 0x05, 0x2a, 0x08, 0x89, 0xa8, 0xd0, 0xd7, 0xb0,
	0xec, 0x91, 0x3f, 0x73, 0x33, 0x55, 0xe2, 0x8c, 0x08, 0x58, 0x8e, 0xc4, 0x57, 0x49, 0x99, 0xf5,
	0x3d, 0x58, 0x31, 0xa8, 0x7d, 0xeb, 0xde, 0xa7, 0x3f, 0xce, 0x12, 0x64, 0x86, 0x09, 0x66, 0x5c,
	0x47, 0xff, 0x0a, 0x56, 0xaf, 0x3d, 0xeb, 0x59, 0x98, 0x0e, 0xea, 0x29, 0xe9, 0x13, 0x3e, 0x0b,
	0xf3, 0xdf, 0x79, 0xc8, 0xe2, 0xd0, 0x1b, 0x97, 0x23, 0x04, 0xf3, 0x9e, 0x35, 0x20, 0x71, 0x92,
	0xe2, 0x7f, 0xb4, 0x06, 0x0b, 0x0e, 0xe9, 0x84, 0x3d, 0x6d, 0x49, 0x96, 0x4a, 0x3c, 0xd0, 0x11,
	0x94, 0x19, 0xf7, 0xa9, 0x98, 0x0d, 0x6e, 0x71, 0xa2, 0xc1, 0xae, 0xb2, 0xbf, 0x74, 0xb8, 0x9e,
	0xd4, 0xa7, 0xda, 0x92, 0xda, 0x56, 0xa4, 0xc4, 0x25, 0x96, 0x7a, 0xa1, 0x5d, 0x28, 0x3a, 0x84,
	0xd9, 0xd4, 0x15, 0x0c, 0x88, 0x67, 0x27, 0x2d, 0x42, 0xbf, 0x80, 0xf2, 0x08, 0xd9, 0xe2, 0xb9,
	0x59, 0x11, 0xde, 0xaf, 0x62, 0x4d, 0x2b, 0x20, 0x36, 0x2e, 0x05, 0xa9, 0x17, 0x3a, 0x83, 0xd5,
	0xc9, 0xc1, 0x63, 0xda, 0x82, 0xe8, 0xdd, 0xc6, 0xc8, 0xd4, 0x0d, 0x07, 0x0d, 0xa3, 0x89, 0xd9,
	0x63, 0xe8, 0x97, 0x00, 0xb6, 0xa0, 0xa0, 0x63, 0x5a, 0x5c, 0xcb, 0x89, 0xe8, 0x95, 0xaa, 0xdc,
	0x16, 0xd5, 0x64, 0x5b, 0x54, 0xdb, 0xc9, 0xb6, 0xc0, 0x85, 0x18, 0x6d, 0x70, 0xf4, 0x6b, 0x28,
	0x31, 0xfb, 0x96, 0x38, 0x61, 0x5f, 0x1a, 0xe7, 0x9f, 0x35, 0x2e, 0x0e, 0xf1, 0x06, 0x47, 0xbf,
	0x82, 0x62, 0xd7, 0xf5, 0x5c, 0x76, 0x2b, 0xad, 0xcb, 0xcf, 0x5a, 0x43, 0x02, 0x37, 0x78, 0x44,
	0x98, 0xa8, 0x1b, 0x21, 0xd3, 0x16, 0x63, 0x42, 0x8a, 0x57, 0xd4, 0x43, 0xb1, 0x31, 0xb5, 0x92,
	0xec, 0xa1, 0x78, 0xa0, 0x7d, 0xc8, 0x0f, 0x08, 0xa7, 0xae, 0xcd, 0xb4, 0x82, 0xa8, 0xd0, 0x52,
	0xd2, 0xbd, 0x0b, 0x21, 0xc6, 0x89, 0x5a, 0xaf, 0x43, 0x29, 0xdd, 0x4f, 0x54, 0x81, 0x8d, 0x56,
	0xfb, 0x12, 0x1b, 0x67, 0xf5, 0x56, 0xdb, 0x68, 0xd7, 0x4d, 0xe3, 0xc6, 0x68, 0x9c, 0x1b, 0xc7,
	0xe7, 0x75, 0x75, 0x0e, 0xbd, 0x80, 0xf5, 0x51, 0x1d, 0x3e, 0xf9, 0xa1, 0x71, 0x53, 0x3f, 0x55,
	0x15, 0xfd, 0x0e, 0x96, 0x93, 0xe6, 0xe1, 0xd0, 0x8b, 0x76, 0x2d, 0xfa, 0x19, 0xac, 0x0c, 0x3b,
	0x3d, 0xb0, 0x3c, 0xb7, 0x4b, 0x18, 0x17, 0xb3, 0x54, 0xc0, 0x6a, 0xa2, 0xb8, 0x88, 0xe5, 0x11,
	0xf8, 0xc1, 0xa7, 0x77, 0xd1, 0x77, 0xc6, 0x27, 0x70, 0x51, 0x82, 0x13, 0x45, 0x02, 0xd6, 0x6f,
	0xa1, 0x80, 0x43, 0xef, 0x94, 0x70, 0xcb, 0xed, 0xcf, 0x5a, 0x9f, 0xe8, 0x37, 0x30, 0x8c, 0x64,
	0x52, 0x99, 0x96, 0x20, 0x40, 0xf1, 0x70, 0x6d, 0x64, 0xde, 0xe2, 0x94, 0xf1, 0x72, 0x30, 0x2a,
	0xd0, 0xff, 0xa5, 0x88, 0x50, 0xb2, 0x68, 0x43, 0x0e, 0x29, 0x29, 0x0e, 0x6d, 0x42, 0xde, 0xf3,
	0x1d, 0x12, 0x2d, 0x1c, 0x49, 0xad, 0x5c, 0xf4, 0x6c, 0x38, 0x68, 0x0f, 0x4a, 0x5e, 0x38, 0xe8,
	0x10, 0x6a, 0xde, 0x5b, 0xfd, 0x50, 0x6e, 0x10, 0xe5, 0x87, 0x39, 0x5c, 0x94, 0xd2, 0x9b, 0x48,
	0x88, 0x0e, 0x20, 0xd7, 0xf5, 0xe9, 0xc0, 0xe2, 0x82, 0x06, 0x29, 0x92, 0xc9, 0x88, 0xd5, 0x37,
	0x42, 0x89, 0x63, 0x90, 0x7e, 0x08, 0x39, 0x29, 0x41, 0xcb, 0x50, 0xbc, 0x6e, 0xb6, 0xae, 0xea,
	0x27, 0x8d, 0x37, 0x8d, 0xfa, 0xa9, 0x3a, 0x87, 0xf2, 0x90, 0xc5, 0xc6, 0xef, 0x55, 0x05, 0x2d,
	0x01, 0x5c, 0xd5, 0xf1, 0x49, 0xbd, 0xd9, 0x36, 0xce, 0xea, 0x6a, 0xe6, 0x38, 0x0f, 0x0b, 0x22,
	0x01, 0xfd, 0x1d, 0x6c, 0x62, 0x12, 0xf8, 0x94, 0x0f, 0xdd, 0xb3, 0xd9, 0x4b, 0x33, 0x3d, 0x45,
	0x99, 0xd9, 0x53, 0xf4, 0x8f, 0x2c, 0x68, 0x93, 0xce, 0xe3, 0x3d, 0x7b, 0x01, 0x79, 0x4a, 0x58,
	0xd8, 0xe7, 0xc9, 0xaa, 0x7d, 0x1d, 0xd3, 0x75, 0x3a, 0x7e, 0x5c, 0x81, 0x85, 0x2d, 0x4e, 0x7c,
	0x54, 0x7e, 0xca, 0xc0, 0xfa, 0x54, 0x08, 0xda, 0x81, 0xa2, 0x4c, 0xc8, 0x4c, 0xb5, 0x09, 0xa4,
	0xa8, 0x19, 0x35, 0xeb, 0x4b, 0x58, 0x4a, 0x00, 0x23, 0x3d, 0x2b, 0xc5, 0x18, 0xd9, 0x39, 0x3c,
	0xa4, 0x5a, 0x56, 0x34, 0xe5, 0xe8, 0x33, 0xd2, 0xad, 0xb6, 0x84, 0x87, 0x21, 0x4d, 0xb5, 0xa8,
	0x94, 0x8c, 0x59, 0x3d, 0x22, 0x3a, 0x5d, 0xc0, 0xc9, 0x53, 0x77, 0x20, 0x27, 0xb1, 0x93, 0x3d,
	0xcd, 0x41, 0xe6, 0xf2, 0xad, 0xaa, 0xa0, 0x35, 0x50, 0x1b, 0xcd, 0x1b, 0xe3, 0xbc, 0x71, 0x6a,
	0x1a, 0xf8, 0xec, 0xfa, 0xa2, 0xde, 0x6c, 0xab, 0x19, 0xb4, 0x09, 0xab, 0xa7, 0xd7, 0x57, 0xe7,
	0x8d, 0x93, 0x88, 0x8a, 0xb8, 0x7e, 0x75, 0x89, 0xdb, 0x8d, 0xe6, 0x99, 0x9a, 0x45, 0x08, 0x96,
	0x1a, 0xcd, 0x76, 0x1d, 0x37, 0x8d, 0x73, 0xb3, 0x8e, 0xf1, 0x25, 0x56, 0xe7, 0xf5, 0x3f, 0xc2,
	0x2a, 0x26, 0x96, 0x63, 0x50, 0xee, 0x76, 0x2d, 0x9b, 0x3f, 0xd3, 0xf8, 0x19, 0x43, 0x5d, 0xb6,
	0x62, 0x17, 0xb2, 0xc6, 0x72, 0xc3, 0x97, 0x12, 0x61, 0x54, 0x65, 0xfd, 0x15, 0xac, 0x8d, 0xc6,
	0x8a, 0xe7, 0x00, 0xc1, 0xbc, 0x63, 0x71, 0x4b, 0x84, 0x2a, 0x61, 0xf1, 0xff, 0xe1, 0x4f, 0x8b,
	0x00, 0x38, 0xf4, 0x5a, 0x84, 0xde, 0xbb, 0x36, 0x41, 0x2d, 0x28, 0x0c, 0xef, 0x23, 0x24, 0xc9,
	0x30, 0x7e, 0x2f, 0x55, 0x86, 0x43, 0x28, 0x17, 0x80, 0xbe, 0xf3, 0x97, 0x7f, 0xff, 0xe7, 0x6f,
	0x99, 0x17, 0x3a, 0x8a, 0x0e, 0x35, 0x56, 0xbb, 0xff, 0xbe, 0x43, 0xb8, 0xf5, 0x7d, 0x74, 0x63,
	0xb2, 0x23, 0xb1, 0x05, 0x7e, 0x07, 0x39, 0x79, 0x44, 0x21, 0x24, 0x4c, 0x47, 0x2e, 0xaa, 0x09,
	0x77, 0x7b, 0xc2, 0xdd, 0x36, 0x7a, 0x39, 0xe9, 0xae, 0xf6, 0x41, 0x16, 0xeb, 0x23, 0x6a, 0xc1,
	0x62, 0x72, 0x4e, 0x20, 0xb9, 0x4a, 0xc6, 0xae, 0xaf, 0xca, 0xfa, 0x98, 0x54, 0xd6, 0x40, 0xaf,
	0x08, 0xef, 0x6b, 0x68, 0x4a, 0xb2, 0x88, 0x00, 0x7c, 0x3a, 0x15, 0x90, 0xfc, 0x4e, 0x9b, 0xb8,
	0x1d, 0x2a, 0x1b, 0x13, 0x5f, 0x18, 0xf5, 0xe8, 0x28, 0xd6, 0xbf, 0x11, 0x9e, 0xbf, 0xd0, 0x77,
	0xa6, 0xe5, 0xed, 0x3a, 0x1f, 0x8f, 0xe2, 0xfb, 0x02, 0xdd, 0x41, 0x29, 0x7d, 0x6c, 0x20, 0x4d,
	0x04, 0x9a, 0x72, 0x7f, 0x3c, 0x19, 0xea, 0x5b, 0x11, 0x6a, 0x4f, 0xff, 0xe2, 0xa9, 0x50, 0x61,
	0xe2, 0x0c, 0xfd, 0x01, 0x0a, 0xc3, 0x93, 0x25, 0x6e, 0xe8, 0xf8, 0x09, 0xf3, 0x64, 0x98, 0xb8,
	0xb1, 0xaf, 0x36, 0x9f, 0x08, 0x83, 0x7e, 0x54, 0x40, 0x1d, 0xa7, 0x25, 0xda, 0x7a, 0x82, 0xad,
	0x32, 0xd6, 0xf6, 0x4c, 0x2e, 0xeb, 0x3f, 0x17, 0x21, 0xab, 0xfa, 0xb7, 0x33, 0x9a, 0x7f, 0x44,
	0x85, 0x75, 0x6c, 0x7a, 0xa4, 0xbc, 0x42, 0x7f, 0x57, 0xa0, 0x94, 0x9e, 0xf8, 0xb8, 0xa4, 0x53,
	0x08, 0x57, 0x79, 0x31, 0x45, 0x13, 0xc7, 0xc6, 0x22, 0xf6, 0x39, 0xfa, 0xed, 0x8c, 0xd8, 0xb5,
	0x88, 0x87, 0xac, 0xf6, 0x21, 0x66, 0xe7, 0xc7, 0x5a, 0x42, 0x3c, 0x56, 0xfb, 0x30, 0x42, 0xcc,
	0x28, 0x4b, 0xcb, 0x41, 0x3e, 0x94, 0xd2, 0xe7, 0x74, 0x9c, 0xd8, 0x94, 0x0b, 0xfb, 0xc9, 0x26,
	0x1c, 0x88, 0xac, 0xbe, 0xd1, 0xbf, 0x9a, 0x95, 0x15, 0x4f, 0x1c, 0x22, 0x1b, 0x16, 0x93, 0x8b,
	0x3c, 0x26, 0xc6, 0xd8, 0x81, 0xfe, 0x79, 0x43, 0x95, 0x04, 0xa2, 0x91, 0xb3, 0xe3, 0x1f, 0x95,
	0xbf, 0x1a, 0x17, 0x78, 0x0b, 0xf2, 0x0e, 0xe9, 0x5a, 0xd1, 0xe2, 0x5f, 0x41, 0xcb, 0x50, 0xae,
	0x14, 0x45, 0x3c, 0xb9, 0x4c, 0xdf, 0xed, 0xc0, 0x36, 0xe4, 0x8e, 0x89, 0x45, 0x09, 0x45, 0xab,
	0x8b, 0x99, 0x4a, 0xd9, 0x0a, 0xf9, 0xad, 0x4f, 0xdd, 0xf7, 0xe2, 0xf7, 0xd8, 0x6e, 0xa6, 0x53,
	0x02, 0x18, 0x02, 0xe6, 0xde, 0xfd, 0x1f, 0x3f, 0x5e, 0x7b, 0xbe, 0x69, 0xf7, 0x5d, 0xe2, 0xf1,
	0x4e, 0x4e, 0x7c, 0x84, 0xd7, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x60, 0xdd, 0x9e, 0xfa,
	0x0e, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RunServiceClient is the client API for RunService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RunServiceClient interface {
	CreateRun(ctx context.Context, in *CreateRunRequest, opts ...grpc.CallOption) (*RunDetail, error)
	GetRun(ctx context.Context, in *GetRunRequest, opts ...grpc.CallOption) (*RunDetail, error)
	ListRuns(ctx context.Context, in *ListRunsRequest, opts ...grpc.CallOption) (*ListRunsResponse, error)
	ArchiveRun(ctx context.Context, in *ArchiveRunRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	UnarchiveRun(ctx context.Context, in *UnarchiveRunRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	DeleteRun(ctx context.Context, in *DeleteRunRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// ReportRunMetrics reports metrics of a run. Each metric is reported in its
	// own transaction, so this API accepts partial failures. Metric can be uniquely
	// identified by (run_id, node_id, name). Duplicate reporting will be
	// ignored by the API. First reporting wins.
	ReportRunMetrics(ctx context.Context, in *ReportRunMetricsRequest, opts ...grpc.CallOption) (*ReportRunMetricsResponse, error)
	ReadArtifact(ctx context.Context, in *ReadArtifactRequest, opts ...grpc.CallOption) (*ReadArtifactResponse, error)
	TerminateRun(ctx context.Context, in *TerminateRunRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	RetryRun(ctx context.Context, in *RetryRunRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type runServiceClient struct {
	cc *grpc.ClientConn
}

func NewRunServiceClient(cc *grpc.ClientConn) RunServiceClient {
	return &runServiceClient{cc}
}

func (c *runServiceClient) CreateRun(ctx context.Context, in *CreateRunRequest, opts ...grpc.CallOption) (*RunDetail, error) {
	out := new(RunDetail)
	err := c.cc.Invoke(ctx, "/api.RunService/CreateRun", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runServiceClient) GetRun(ctx context.Context, in *GetRunRequest, opts ...grpc.CallOption) (*RunDetail, error) {
	out := new(RunDetail)
	err := c.cc.Invoke(ctx, "/api.RunService/GetRun", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runServiceClient) ListRuns(ctx context.Context, in *ListRunsRequest, opts ...grpc.CallOption) (*ListRunsResponse, error) {
	out := new(ListRunsResponse)
	err := c.cc.Invoke(ctx, "/api.RunService/ListRuns", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runServiceClient) ArchiveRun(ctx context.Context, in *ArchiveRunRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.RunService/ArchiveRun", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runServiceClient) UnarchiveRun(ctx context.Context, in *UnarchiveRunRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.RunService/UnarchiveRun", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runServiceClient) DeleteRun(ctx context.Context, in *DeleteRunRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.RunService/DeleteRun", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runServiceClient) ReportRunMetrics(ctx context.Context, in *ReportRunMetricsRequest, opts ...grpc.CallOption) (*ReportRunMetricsResponse, error) {
	out := new(ReportRunMetricsResponse)
	err := c.cc.Invoke(ctx, "/api.RunService/ReportRunMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runServiceClient) ReadArtifact(ctx context.Context, in *ReadArtifactRequest, opts ...grpc.CallOption) (*ReadArtifactResponse, error) {
	out := new(ReadArtifactResponse)
	err := c.cc.Invoke(ctx, "/api.RunService/ReadArtifact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runServiceClient) TerminateRun(ctx context.Context, in *TerminateRunRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.RunService/TerminateRun", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runServiceClient) RetryRun(ctx context.Context, in *RetryRunRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.RunService/RetryRun", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RunServiceServer is the server API for RunService service.
type RunServiceServer interface {
	CreateRun(context.Context, *CreateRunRequest) (*RunDetail, error)
	GetRun(context.Context, *GetRunRequest) (*RunDetail, error)
	ListRuns(context.Context, *ListRunsRequest) (*ListRunsResponse, error)
	ArchiveRun(context.Context, *ArchiveRunRequest) (*empty.Empty, error)
	UnarchiveRun(context.Context, *UnarchiveRunRequest) (*empty.Empty, error)
	DeleteRun(context.Context, *DeleteRunRequest) (*empty.Empty, error)
	// ReportRunMetrics reports metrics of a run. Each metric is reported in its
	// own transaction, so this API accepts partial failures. Metric can be uniquely
	// identified by (run_id, node_id, name). Duplicate reporting will be
	// ignored by the API. First reporting wins.
	ReportRunMetrics(context.Context, *ReportRunMetricsRequest) (*ReportRunMetricsResponse, error)
	ReadArtifact(context.Context, *ReadArtifactRequest) (*ReadArtifactResponse, error)
	TerminateRun(context.Context, *TerminateRunRequest) (*empty.Empty, error)
	RetryRun(context.Context, *RetryRunRequest) (*empty.Empty, error)
}

// UnimplementedRunServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRunServiceServer struct {
}

func (*UnimplementedRunServiceServer) CreateRun(ctx context.Context, req *CreateRunRequest) (*RunDetail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRun not implemented")
}
func (*UnimplementedRunServiceServer) GetRun(ctx context.Context, req *GetRunRequest) (*RunDetail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRun not implemented")
}
func (*UnimplementedRunServiceServer) ListRuns(ctx context.Context, req *ListRunsRequest) (*ListRunsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRuns not implemented")
}
func (*UnimplementedRunServiceServer) ArchiveRun(ctx context.Context, req *ArchiveRunRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArchiveRun not implemented")
}
func (*UnimplementedRunServiceServer) UnarchiveRun(ctx context.Context, req *UnarchiveRunRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnarchiveRun not implemented")
}
func (*UnimplementedRunServiceServer) DeleteRun(ctx context.Context, req *DeleteRunRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRun not implemented")
}
func (*UnimplementedRunServiceServer) ReportRunMetrics(ctx context.Context, req *ReportRunMetricsRequest) (*ReportRunMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportRunMetrics not implemented")
}
func (*UnimplementedRunServiceServer) ReadArtifact(ctx context.Context, req *ReadArtifactRequest) (*ReadArtifactResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadArtifact not implemented")
}
func (*UnimplementedRunServiceServer) TerminateRun(ctx context.Context, req *TerminateRunRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TerminateRun not implemented")
}
func (*UnimplementedRunServiceServer) RetryRun(ctx context.Context, req *RetryRunRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetryRun not implemented")
}

func RegisterRunServiceServer(s *grpc.Server, srv RunServiceServer) {
	s.RegisterService(&_RunService_serviceDesc, srv)
}

func _RunService_CreateRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunServiceServer).CreateRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.RunService/CreateRun",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunServiceServer).CreateRun(ctx, req.(*CreateRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunService_GetRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunServiceServer).GetRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.RunService/GetRun",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunServiceServer).GetRun(ctx, req.(*GetRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunService_ListRuns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRunsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunServiceServer).ListRuns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.RunService/ListRuns",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunServiceServer).ListRuns(ctx, req.(*ListRunsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunService_ArchiveRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunServiceServer).ArchiveRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.RunService/ArchiveRun",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunServiceServer).ArchiveRun(ctx, req.(*ArchiveRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunService_UnarchiveRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnarchiveRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunServiceServer).UnarchiveRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.RunService/UnarchiveRun",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunServiceServer).UnarchiveRun(ctx, req.(*UnarchiveRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunService_DeleteRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunServiceServer).DeleteRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.RunService/DeleteRun",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunServiceServer).DeleteRun(ctx, req.(*DeleteRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunService_ReportRunMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportRunMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunServiceServer).ReportRunMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.RunService/ReportRunMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunServiceServer).ReportRunMetrics(ctx, req.(*ReportRunMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunService_ReadArtifact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadArtifactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunServiceServer).ReadArtifact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.RunService/ReadArtifact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunServiceServer).ReadArtifact(ctx, req.(*ReadArtifactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunService_TerminateRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunServiceServer).TerminateRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.RunService/TerminateRun",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunServiceServer).TerminateRun(ctx, req.(*TerminateRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunService_RetryRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunServiceServer).RetryRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.RunService/RetryRun",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunServiceServer).RetryRun(ctx, req.(*RetryRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RunService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.RunService",
	HandlerType: (*RunServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRun",
			Handler:    _RunService_CreateRun_Handler,
		},
		{
			MethodName: "GetRun",
			Handler:    _RunService_GetRun_Handler,
		},
		{
			MethodName: "ListRuns",
			Handler:    _RunService_ListRuns_Handler,
		},
		{
			MethodName: "ArchiveRun",
			Handler:    _RunService_ArchiveRun_Handler,
		},
		{
			MethodName: "UnarchiveRun",
			Handler:    _RunService_UnarchiveRun_Handler,
		},
		{
			MethodName: "DeleteRun",
			Handler:    _RunService_DeleteRun_Handler,
		},
		{
			MethodName: "ReportRunMetrics",
			Handler:    _RunService_ReportRunMetrics_Handler,
		},
		{
			MethodName: "ReadArtifact",
			Handler:    _RunService_ReadArtifact_Handler,
		},
		{
			MethodName: "TerminateRun",
			Handler:    _RunService_TerminateRun_Handler,
		},
		{
			MethodName: "RetryRun",
			Handler:    _RunService_RetryRun_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/kubeflow/pipelines/backend/api/run.proto",
}
